name: Cobhan-Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published] # Trigger when release is created

jobs:
  test-linux:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [stable, oldstable]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: 'true'
    - name: Test Cobhan
      run: scripts/test.sh
  test-macos:
    timeout-minutes: 15
    runs-on: 'macos-latest'
    strategy:
      matrix:
        go-version: [stable, oldstable]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: 'true'
    - name: Test Cobhan
      run: scripts/test.sh
